cmapi.channel["map.feature.edit"] = {
  schema: {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "map.feature.edit",
    "description": "Message to notify the map to begin editing an existing feature. The map is responsible for providing the user interface to enable visual editing of the feature.",
    "type": "object",
    "properties": {
      "overlayId": {
        "description": "The id of the overlay containing the feature that is to be edited.  If no overlayId is included, default overlay with ID equal to sending widget's ID is used. If an overlay exists, it will retain its status (whether visible or hidden). If an overlay with this ID does not exist, an error is sent on the map.error channel",
        "type": "string",
		"default": "Sending widget's ID"
      },
      "featureId": {
        "description": "The unique identifier for the feature to be edited. ",
        "type": "string"
      },
      "messageId": {
        "description": "A globally unique ID that identifies this particular message and which MUST be used in the associated map.message.complete, map.message.progress, and map.message.cancel messages as defined in the map.message channels.",
        "type": "string"
      }
    },
    "required": ["featureId", "messageId"]
  },
  notes: [
    "If a widget sends a map.feature.edit message, the map widget SHALL go into edit mode for the feature identified by the featureId.",
    "When the feature is placed into edit mode the Map SHALL issue a map.message.progress message using the messageId provided by the originating edit request, along with all the feature properties set to the current values in order to indicate to client widgets that the edit operation has started.",
	"If the edit mode was initiated by the map itself (i.e., not via an external widget), then the messageId sent in the map.message.progress and map.message.complete messages will be generated by the map.",
    "During edit mode, for each user modification of the feature (e.g., moving a point, adding some text, adding a new point, etc.) a map SHALL send a map.message.progress message.  This SHALL occur each time the feature is manipulated during an edit. For instance, if a point of a line is moved to a new location, a map.message.progress message will be sent.",
    "An edit procedure may be cancelled by issuing a map.message.cancel message",  
	"If the edit mode is cancelled for any reason before the edit is complete, the map SHALL issue a map.message.complete message with the messageId of the original map.feature.edit message and a status of 'cancelled'.  The details object of the map.message.complete message SHALL contain the original coordinates of the feature (i.e., before the edit began)",
    "If the edit is completed, the map SHALL issue a map.message.complete with the messageId of the original map.feature.edit message and the final coordinates of the edited feature",
    "If the edit is completed, the map SHALL additionally send a map.feature.plot message so that other widgets receive the final state of the edited feature.  The map SHALL NOT issue a map.feature.plot message if the edit was cancelled."
  ],
  "changeLog": [{
    "version": "1.3.0",
    "change": "This channel is new"
  }]
};
